language: scala

dist: trusty
sudo: required

os:
- linux

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

script:
- sbt test it:test
# Following recommendations from http://scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html.
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# TODO: Employ whatever solution from travis-ci/travis-ci#929 to perform these tasks once.
# TODO: Enable once Coveralls supports Jacoco reports.
after_success:
- jdk_switcher use oraclejdk8
- sbt publish

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

env:
  global:
  # Encrypted COVERALLS_REPO_TOKEN for repository.
  - secure: "fxRNy/fNLE1WJEI4fm/5WKZs7vxCeCOJC/ryAJnv78+ec8USpNcd19pRjIYSj5ZJIWoInT9xPOv0t+V9Q/Lk0fs0/Ngu0nuFkaMJyq2xog0uzxcJhs849PVNt2hwtTO4y+JJNsV/PZ6/oFGe378yfSb/DsfUBNYAwImHFSsQLCtAqwPG/0/VUR7qvFDWgob5vV4FtMXwiZHsNEmh6Gqgz3sA3E79X9OFnEZS7ARpACFSMTZ1ZV/UbrtTnNr0Sewr4gA9t2nVTO7Owa2wyPY3HbaEhsH6zYyH3m4gI4Qr3GD1aBI026q0ZI1OmLlvjTMvjaUWAhpD4ioa0fMeC85tVs6oRxZ/2W2ImYDl7LqsM5ceegH14QWIWKlfLGWlhymFHOZwJTX2JGNJqsTwvkJyKwTAA8bGUiXBEl+30HIV1vEIxbUiKxsSVytK2THunL/JdWAWywO6zLDDJzqhgfHfEvYM7Zf0CM2yIeLxhTUB/V8WJ3rDCOAPAF4fGmSEL+7NYdHBcC3QHUr8cOf8DGwsSRO0ioWZRIgbShztavyVk/GGZvhhnbRYH8wzDq365lV8eNTHuRTmUQ5mpyHre1yYVQMaOZGOtJ8wvMkbWe+JBuqAvzEPyq72nkKurQsLx/E5G+cxr25+t4eMHsF7vMZfIdhP0f+g0kqXpaMmdMp2qzM="
  # Encrypted AWS_ACCESS_KEY_ID for publish to S3.
  - secure: "GUFr7Xn1brIgc4joHbTC6ffOm3eUNuNYnoe6HxdkXU/+hiABV6oGP40UVrfggdH2RH1QY7uigcCVJl8Sf67QR3XfxF6/zc4GjLe39Y8NgjKHTAD4FB/RGQMjDAxKzxRrmCAhcqXTbbxJuo1ehrbiGMU+GysUNt/W+KYS/PAP/MKEMUlPYPHAOhQWoH3gXpF4fInnorbtbthm5Y3u2D6L8AniaOpmc+z2Kgmc5zbXIJLDVu4VJJqfFnO/KnLC2conxBnJ9YWN7alTHN4hUP4jSpaaQelKM/NS8lUuvvKfFAduWF5JltkZm+JP9kgcw1yvH9Vrv/pd5U86hCU5gMpQ/T4ijxhAXcfyxtZOxfnC5mdyX2FI5X338Y3AJ6sRsxQqAbEHsDzwlA4Y3RqNx0KtQ7SNJK8plTyy65t8k/s2V5dBd6CilF811YBeKj+EqXPFbZ3ne+0rrav9Ny/OyX5mY2g62RQ92zbgBU3Ci0iN6O7E2dQPOw2fpxJR/n3pCpcsqFfSbtx6UAkOtqa1U96Cw5zxXtJNITMQO+JuQG1xeJbesnmH5gmQUT1N+GDJj7f5S8BGZm2IqLNPaG57nD9OhUAGHWyn6whIDYV+MOOVcx/s2yHxE+5r8buWsvyi9+t3lJ1KdVjwWtEu5e40Mpy1zOb0dHh/wtfpOeGWjam8xQw="
  # Encrypted AWS_SECRET_ACCESS_KEY for publish to S3.
  - secure: "MZKC/0max6B3vtGQwM5MMwkkFDhJYG6wlcY9J9HGeeTGsxhvZUSiposcpdwDOVT49g4TRl8S6hZ7WDUbqkPj5WJMpsdhV28BSSfRiP5ZCRrWJ5xlqgwk61j7f5GXYw1ppgsMenRtUyER5FM+OQH63NjVQZEN0TkSyQ6PFb3PLBMwP3F3L/rl+RQDwP48cnl7Z+5zEEiyA9eTXNlnwyc3JgqnsZ6Pls48HhkRf6iTA7ZAqXMZZzWLrWpgbS5e3oEHvWNB8vNRsyyCuCsAmwjqfIjw2jrCgDaNblPvBBrrHTIoeOJHOLRyDlmHPdd07TJYNB3Cu38TSmm/wzilU5CRGW0Ra5xeS7rqrsQ8EQHB/35wRsj4DOnNcNlOkORHZVVZtZQKqkW+57G5+IJ7B/1J+O2vGHQ+rbhPLEKczwedly3v56ZunfYV1gnDUj9eOw6QV40B62Z+oD2wzH6wTRLJRTvmYaBCQxQeMXP9tkxxxvKJz/pNhyA3qAp9oCKT12Mxb3okKadyu4SU0PivC8qPBCBvlK7H+81JHuqMJT7Wo2296hOAdsPnyEjMI+kqwq/0ZiRvS+U3K2odD3wz6cjLYESdVss5k4W6IC29wBGoYSRFR1GXFvhaTAq2udPtsRPNhCUiB+YPGH/XT+lTkXmZNY0uMGzPfi966m1LtMgOt38="
