language: scala

dist: trusty
sudo: required

os:
- linux

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

script:
- sbt test it:test
# Following recommendations from http://scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html.
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# TODO: Employ whatever solution from travis-ci/travis-ci#929 to perform these tasks once.
# TODO: Enable once Coveralls supports Jacoco reports.
# Only publish (snapshots) when on master or a maintenance branch.
after_success:
- jdk_switcher use oraclejdk8
- echo "TRAVIS_BRANCH: $TRAVIS_BRANCH"
- echo "TRAVIS_TAG: $TRAVIS_TAG"
- "[[ $TRAVIS_BRANCH =~ (master|^v[0-9]+.[0-9]+) ]] && sbt publish"

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

env:
  global:

  # Encrypted COVERALLS_REPO_TOKEN for repository.
  - secure: "fxRNy/fNLE1WJEI4fm/5WKZs7vxCeCOJC/ryAJnv78+ec8USpNcd19pRjIYSj5ZJIWoInT9xPOv0t+V9Q/Lk0fs0/Ngu0nuFkaMJyq2xog0uzxcJhs849PVNt2hwtTO4y+JJNsV/PZ6/oFGe378yfSb/DsfUBNYAwImHFSsQLCtAqwPG/0/VUR7qvFDWgob5vV4FtMXwiZHsNEmh6Gqgz3sA3E79X9OFnEZS7ARpACFSMTZ1ZV/UbrtTnNr0Sewr4gA9t2nVTO7Owa2wyPY3HbaEhsH6zYyH3m4gI4Qr3GD1aBI026q0ZI1OmLlvjTMvjaUWAhpD4ioa0fMeC85tVs6oRxZ/2W2ImYDl7LqsM5ceegH14QWIWKlfLGWlhymFHOZwJTX2JGNJqsTwvkJyKwTAA8bGUiXBEl+30HIV1vEIxbUiKxsSVytK2THunL/JdWAWywO6zLDDJzqhgfHfEvYM7Zf0CM2yIeLxhTUB/V8WJ3rDCOAPAF4fGmSEL+7NYdHBcC3QHUr8cOf8DGwsSRO0ioWZRIgbShztavyVk/GGZvhhnbRYH8wzDq365lV8eNTHuRTmUQ5mpyHre1yYVQMaOZGOtJ8wvMkbWe+JBuqAvzEPyq72nkKurQsLx/E5G+cxr25+t4eMHsF7vMZfIdhP0f+g0kqXpaMmdMp2qzM="

  # Encrypted AWS_ACCESS_KEY for publish to S3.
  - secure: "w94eM3momIVeZLtXGB+P5evdxp3W3X+ZUowZvdMMXa21FOSgToTalzO6FiI+ymFVOf9BFEztGT39j+1q9c+12oMtxF+uRdeHep7s2oZ6+aqWUnwJ82w++PoQmarQP+IvVTkmZ8e6TW493oblBoxDD4RMVN7OnuUEYXqTCU/o5BKoatnF1NXCw2V6PqrNN4oxUib6ypnp4pRkIZEDT7e+g6rY+xP2TPWQeGew6FsbhWkoWG+vO+83M3fZaEfh3aB9mEYEacLBZMW19KolPNQkxAjJCZmRMK+Ay4eCcf1vmmO4b2/01YP4Iokau38lruyXoICiijFbh8MHzX+xkXp/gUZpA69gyazajpQlJ/G/mhlK2gdGFZANghvvWM7j990zmmOTp9gEEgatMWX1aeWyVScmt8MXgHhyfQSkZZL9Kp+ZeepuFGaMM4oAVwCcxW9VgjuErjPn2lkgmQyITgdLe9Mmb5v3+FTj8DhTIrnIvSoSZMuwhdTGiHqZuX7WBCZd4iwohqIxj+B5n91xEVZleV2dAzA8Q/q1oql2oZuFjXyD+iBlqZXjoTLn6qYY9AGaZPA0ZnAWdxonmNyTl+CHztGT0/3qlT8i/COyDCUgvNn+PQNUAYwM/dfQLhmQwkjENo3A9Bnp+ekbfTZ5zhrqqSkCiI0U+8HlNo1NXBvxBxk="

  # Encrypted AWS_SECRET_KEY for publish to S3.
  - secure: "xu2XS+fENsrFHFPFJce6vY2flhFH2pedHiOyHkSei8Q2v0G9JSlLDrcF3VI580iJCyeH7/arN/uWWwyxJS+PwY7QOStEg4ch70EkLBfBmy2QceJ7QMRZvVRB3A/Zt2yByTM0XNAsBoE2EX1mp2mQEdoWvu20o43xd93E/LuQGI63ydWZRo6SgYyvYZ1rjSXOYxH2Y/TtbXihVmPzjBczwZPhP0dMuoQlMgFWngRLLdK11JDLxEwVc6J2Iidva1Q/qEQIspnBq3dC82ADCNEMm/2BT22rrcefQ8DS5EubSR2iO9pX+MUBwnKZO5xPj7WxYd0TAW0/0/msu3tThrtqJ1a5Q0xMQH7sgHYl131Jt/RMRr+WMN5Qo+uNYJZha9so5XNArvCcRJGMjJgcoHNzhfDMNnNrJvxJMwn1Xp0A77QhOUxVRzBuF4TsQgBZHVydA3l/rqoALsvlru+X6OwRvJKvmrR2aRAWX0XKhSUBLrgcq/POJvAE0zqQiXALeL9a49L2DjXaR/FE2XMR8TLk6072Xtde+2kQGLBIJlkTvpZVD5TtLSSc1vFqzWgsUhRAmhYcUx9l6vBrrUeSPOGzCpcj90k6Pjkk5BvLMOpaCBpQiMJOVuvdkg1mN8YiPjciETXfkgJcID7rHEqWvWU62nmHJXEfvlxfPN2oSJBhq04="
