language: scala

#dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode7.2

script:
- sbt test it:test
# Following recommendations from http://scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html.
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
# TODO: Enable once Coveralls supports Jacoco reports.
# Coverage resets the Scala version, despite SBT argument. Therefore, perform coverage report and publish after successful test. Eventually, perform this after successful matrix (see travis-ci/travis-ci#929).
# - sbt clean coverage test coverageReport coveralls

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

env:
  global:
  # Encrypted COVERALLS_REPO_TOKEN for repository.
  - secure: "fxRNy/fNLE1WJEI4fm/5WKZs7vxCeCOJC/ryAJnv78+ec8USpNcd19pRjIYSj5ZJIWoInT9xPOv0t+V9Q/Lk0fs0/Ngu0nuFkaMJyq2xog0uzxcJhs849PVNt2hwtTO4y+JJNsV/PZ6/oFGe378yfSb/DsfUBNYAwImHFSsQLCtAqwPG/0/VUR7qvFDWgob5vV4FtMXwiZHsNEmh6Gqgz3sA3E79X9OFnEZS7ARpACFSMTZ1ZV/UbrtTnNr0Sewr4gA9t2nVTO7Owa2wyPY3HbaEhsH6zYyH3m4gI4Qr3GD1aBI026q0ZI1OmLlvjTMvjaUWAhpD4ioa0fMeC85tVs6oRxZ/2W2ImYDl7LqsM5ceegH14QWIWKlfLGWlhymFHOZwJTX2JGNJqsTwvkJyKwTAA8bGUiXBEl+30HIV1vEIxbUiKxsSVytK2THunL/JdWAWywO6zLDDJzqhgfHfEvYM7Zf0CM2yIeLxhTUB/V8WJ3rDCOAPAF4fGmSEL+7NYdHBcC3QHUr8cOf8DGwsSRO0ioWZRIgbShztavyVk/GGZvhhnbRYH8wzDq365lV8eNTHuRTmUQ5mpyHre1yYVQMaOZGOtJ8wvMkbWe+JBuqAvzEPyq72nkKurQsLx/E5G+cxr25+t4eMHsF7vMZfIdhP0f+g0kqXpaMmdMp2qzM="
