version: '{build}'

image: Visual Studio 2008

build_script:
- bin\activator clean compile

test_script:
- bin\activator test it:test

cache:
- C:\Users\appveyor\.ivy2
- C:\Users\appveyor\.m2
- C:\Users\appveyor\.sbt
