version: '{build}'

os: Windows Server 2012

build_script:
- bin\activator clean compile

test_script:
- bin\activator test
- bin\activator it:test

cache:
- C:\Users\appveyor\.ivy2
- C:\Users\appveyor\.m2
- C:\Users\appveyor\.sbt
